---
# This playbook installs Docker on target hosts using the geerlingguy.docker role.

# Ensure the geerlingguy.docker role is installed via ansible-galaxy before running this playbook.
# Example: ansible-galaxy role install geerlingguy.docker

- name: Install Docker using geerlingguy.docker role # Added a descriptive name for the play
  hosts: "{{ target_host | default('all') }}" # Allow specifying target host via variable, default to 'all'
  become: yes # Use privilege escalation (sudo) to install packages and manage services

  vars:
    # Define the user to be added to the 'docker' group.
    # This variable will use the value of 'docker_user_var' if passed,
    # otherwise it will default to 'trasba'.
    docker_user_var: "{{ docker_user | default('trasba') }}"

  roles:
    # Include the geerlingguy.docker role.
    # This role handles the steps required to install Docker Engine.
    - role: geerlingguy.docker
      # Pass variables here to customize the role's behavior.
      # Refer to the geerlingguy.docker role documentation for available variables.

      # Add the specified user to the 'docker' group.
      docker_users:
        - "{{ docker_user_var }}"

      # Example of other variables (uncomment and modify as needed):
      # docker_edition: "ce" # Use Community Edition (default)
      # docker_package_state: "present" # Ensure package is installed (default)
