---
- name: System Maintenance and Kernel Updates
  hosts: "{{ target_host | default('all') }}"
  become: yes
  gather_facts: yes

  # Safety check: Ensure the user specified a host in Semaphore
  pre_tasks:
    - name: Verify target_host is defined
      ansible.builtin.fail:
        msg: "Target host is not defined. Please specify a host or group (e.g., pi-01)."
      when: target_host is not defined or target_host == ""

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Perform full system upgrade
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: apt_result

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Maintenance Summary
      ansible.builtin.debug:
        msg: 
          - "Host:            {{ inventory_hostname }}"
          - "OS Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Packages Changed: {{ apt_result.changed }}"
          - "Reboot Required: {{ reboot_required_file.stat.exists }}"

    - name: Notify if reboot is needed
      ansible.builtin.debug:
        msg: "!!! WARNING: Reboot is required on {{ inventory_hostname }} to apply Kernel/System updates !!!"
      when: reboot_required_file.stat.exists