---
# This is the master playbook that imports other playbooks for a full server setup and hardening workflow.
# secure_ssh, apt_upgrade, inst_docker, docker_ipv6
- name: Full Server Setup and Hardening Workflow
  hosts: "{{ target_host }}" # target_host is mandatory. If not provided, Ansible will error.
  gather_facts: false # No need to gather facts at this top level, as each imported playbook will do it if needed.
  become: yes # All included playbooks require become, so ensure it here.

- import_playbook: secure_sshd.yml
- import_playbook: apt_upgrade.yml
- import_playbook: inst_docker/inst_docker.yml
- import_playbook: docker_ipv6.yml
