---
# This is the master playbook that imports other playbooks for a full server setup and hardening workflow.
# secure_ssh, apt_upgrade, inst_docker, docker_ipv6
- name: Full Server Setup and Hardening Workflow
  hosts: "{{ target_host }}" # target_host is mandatory. If not provided, Ansible will error.
  gather_facts: false # No need to gather facts at this top level, as each imported playbook will do it if needed.
  become: yes # All included playbooks require become, so ensure it here.

  vars:
    # Variables defined here are available to all imported playbooks.
    # The 'target_host' variable will be passed from the command line/Semaphore arguments.
    # It will automatically be available to all imported playbooks.
    # No need to redefine it within each 'import_playbook' task's vars.

    # Define default for docker_user_var, and allow override from CLI
    default_docker_user: "trasba"
    # This variable will be used by inst_docker.yml.
    # Its value will come from 'docker_user' (if provided from Semaphore)
    # or fall back to 'default_docker_user'.
    docker_user: "{{ docker_user | default(default_docker_user) }}"

  tasks:
    - name: Run secure_sshd.yml to harden SSH
      import_playbook: gather_basic_info.yml

    - name: Run secure_sshd.yml to harden SSH
      import_playbook: secure_sshd.yml

    - name: Run apt_upgrade.yml to update and upgrade packages
      import_playbook: apt_upgrade.yml

    - name: Run inst_docker/inst_docker.yml to install Docker
      import_playbook: inst_docker/inst_docker.yml

    - name: Run docker_ipv6 to add ipv6 functionality to Docker
      import_playbook: docker_ipv6.yml
