---
- name: Secure SSH Server with Key-Based Authentication
  hosts: "{{ target_host | default('all') }}" # Allow specifying target host
  become: yes
  #become_method: sudo
  #become_user: root
  become_ask_pass: false #we are providing the password through variable.
  vars:
    become_pass: "{{ vault_become_password }}" # vault_become_password is the variable name in Semaphore UI vault.
  tasks:
    - name: Ensure PubkeyAuthentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PubkeyAuthentication'
        line: PubkeyAuthentication yes
      notify: Restart sshd
      
    - name: Ensure PasswordAuthentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: PasswordAuthentication no
      notify: Restart sshd

    - name: Ensure ChallengeResponseAuthentication is disabled (if present)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: ChallengeResponseAuthentication no
        state: present
      notify: Restart sshd
      ignore_errors: true # In case the line is not there.

    - name: Ensure UsePAM is disabled (if present)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^UsePAM'
        line: UsePAM no
        state: present
      notify: Restart sshd
      ignore_errors: true # In case the line is not there.

    - name: Ensure PermitRootLogin is set to no (optional, for added security)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: PermitRootLogin no
      notify: Restart sshd
      ignore_errors: true # In case the line is not there.

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
