---
- name: Raspberry Pi Provisioning
  hosts: "{{ target_host }}"
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: Ensure target_host is defined
      ansible.builtin.fail:
        msg: "Please specify a 'target_host' (e.g., pi-01)."
      when: target_host is not defined or target_host == ""

  roles:
    - role: common
    - role: security
    - role: geerlingguy.docker
      vars:
        # This converts a single string into a list, 
        # but keeps a list as a list.
        docker_users: "{{ [docker_users] | flatten }}"

        docker_daemon_options:
          ipv6: true
          fixed-cidr-v6: "fd00:1410::/48"
          # Adding experimental is often required for IPv6 NAT/Routing in newer Docker versions
          experimental: true 
          ip6tables: true